<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="SingleSignalToLED" Id="{3cf7ba2c-e8e2-4a18-9731-d83d473d63c3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION SingleSignalToLED : INT
VAR_INPUT
	LEDSignal	:	USINT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// convert standard 0-255 LED signals to INT datatype
SingleSignalToLED := LEDSignal/256 * 32767;]]></ST>
    </Implementation>
    <LineIds Name="SingleSignalToLED">
      <LineId Id="7" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>