<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="LEDStateMachine" Id="{11a7e2b3-5e04-4b6a-9c94-27e77c703e44}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK LEDStateMachine
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="LEDStateMachine">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>