<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="LEDs" Id="{080668ae-5330-4f9e-94a4-ce20fb139d33}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM LEDs
VAR	
	Red		AT%Q*	:	INT;
	Green	AT%Q*	:	INT;
	Blue	AT%Q*	:	INT;
	White	AT%Q*	:	INT;
	
	countdown	:	Countdown;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[countdown(RedOut => Red,GreenOut => Green, BlueOut => Blue,WhiteOut => White);]]></ST>
    </Implementation>
    <LineIds Name="LEDs">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>