<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="RGBWtoINT" Id="{0750f7b7-a3ac-47d5-a092-a91a39eece94}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION RGBWtoINT : INT
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="RGBWtoINT">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>